# Base configs
baseurl: "https://tballast.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-151267666-1"

# UI configs
title: "Photography by Tyler Ballast "
subtitle: "Keep your stick on the ice"
author: "Tyler Ballast"
header:
 title: "Photography"
 subtitle: "by Tyler Ballast"
footer:
 name: "Hey there, my name is Tyler"
 bio: "I bought a camera, and what you see here are my attempts to use it."
 # github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  # facebook: "https://www.facebook.com/t"
  instagram: "https://www.instagram.com/tylerballast"
  # dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://in.linkedin.com/in/tylerballast"
  github: "https://www.github.com/tballast"
